CREATE SCHEMA "courses";

CREATE TABLE "courses"."Users" (
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "FirstName" varchar(50) NOT NULL,
  "LastName" varchar(50) NOT NULL,
  "Email" varchar(100) NOT NULL,
  "Password" varchar(100) NOT NULL,
  "CreatedOn" timestamp NOT NULL,
  "ModifiedOn" timestamp
);

CREATE TABLE "courses"."UserCourses" (
  "UserId" integer NOT NULL,
  "CourseId" integer NOT NULL,
  "CreatedOn" timestamp NOT NULL,
  PRIMARY KEY ("UserId", "CourseId")
);

CREATE TABLE "courses"."Categories" (
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "Name" varchar(100) NOT NULL,
  "CreatedOn" timestamp NOT NULL
);

CREATE TABLE "courses"."Courses" (
  "Id" integer GENERATED BY DEFAULT AS identity PRIMARY KEY NOT NULL,
  "Name" varchar(150) NOT NULL,
  "Description" varchar(1000) NOT NULL,
  "CreatedOn" timestamp NOT NULL,
  "ModifiedOn" timestamp,
  "CategoryId" integer NOT NULL
);

CREATE TABLE "courses"."Videos" (
  "Id" integer PRIMARY KEY NOT NULL,
  "Title" varchar(150) NOT NULL,
  "Url" varchar(200) NOT NULL,
  "CreatedOn" timestamp NOT NULL,
  "CourseId" integer NOT NULL
);

ALTER TABLE "courses"."UserCourses" ADD FOREIGN KEY ("UserId") REFERENCES "courses"."Users" ("Id");

ALTER TABLE "courses"."UserCourses" ADD FOREIGN KEY ("CourseId") REFERENCES "courses"."Courses" ("Id");

ALTER TABLE "courses"."Courses" ADD FOREIGN KEY ("CategoryId") REFERENCES "courses"."Categories" ("Id");

ALTER TABLE "courses"."Videos" ADD FOREIGN KEY ("CourseId") REFERENCES "courses"."Courses" ("Id");
